insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (1, 'Berge Group', '8816 Briar Crest Hill');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (2, 'Yundt, Cruickshank and Wolff', '1571 Forest Dale Plaza');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (3, 'Cummerata, Dickinson and Zboncak', '4 Chive Crossing');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (4, 'Batz-Cronin', '6 Troy Avenue');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (5, 'Effertz-Schultz', '98 Mesta Road');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (6, 'Braun, Leuschke and Cormier', '78 Valley Edge Road');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (7, 'Ernser, Ferry and Kihn', '0 Anzinger Plaza');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (8, 'Cronin, Langosh and Berge', '1 Maple Avenue');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (9, 'Kemmer, Rogahn and Durgan', '27 Lunder Parkway');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (10, 'Nader-Shields', '33 Dottie Pass');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (11, 'D''Amore, Feest and Schiller', '0752 Waubesa Avenue');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (12, 'Stanton, McClure and Price', '91 Elka Center');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (13, 'Jaskolski, Kiehn and Quigley', '1 Waxwing Alley');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (14, 'Mertz, Kshlerin and Rutherford', '04774 Muir Place');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (15, 'Simonis and Sons', '7 Grover Road');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (16, 'Kilback, Stoltenberg and Jacobs', '9751 Elgar Avenue');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (17, 'Schamberger and Sons', '16951 American Pass');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (18, 'Abshire, Morissette and Hilpert', '32994 Pankratz Terrace');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (19, 'Bradtke-Heaney', '314 Scofield Park');
insert into nocleg (nocleg_id, nazwa, adres_wycieczki) values (20, 'Ryan, Pollich and Lehner', '093 Mendota Place');
