insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (1, 'Pagac, Schimmel and Homenick', '04096 Hovde Lane', 'njeandeau0@imageshack.us', '9752852512');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (2, 'Barton, Ferry and Swift', '59673 La Follette Pass', 'rjoynes1@dropbox.com', '6223133314');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (3, 'Hoppe, Strosin and Schiller', '510 Loomis Circle', 'bfavelle2@ehow.com', '6797045499');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (4, 'Zieme, Sporer and Metz', '1507 Fieldstone Avenue', 'jtwining3@mozilla.com', '6181240616');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (5, 'Steuber-West', '18632 Johnson Terrace', 'gcorran4@mac.com', '4942290672');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (6, 'Lindgren Group', '24396 Judy Drive', 'rskynner5@sogou.com', '3141370992');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (7, 'Torp Group', '08222 Dahle Terrace', 'wfinan6@china.com.cn', '4577466485');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (8, 'Williamson-Rowe', '73 Monica Circle', 'jbreckwell7@marriott.com', '1166947244');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (9, 'Kuvalis-Hoeger', '28018 Aberg Hill', 'sgallally8@google.com.br', '4853422494');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (10, 'Windler, Frami and Rohan', '80 Superior Drive', 'rarnefield9@senate.gov', '5383796796');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (11, 'Ondricka and Sons', '76 Bluestem Crossing', 'hloggiea@cornell.edu', '8281703183');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (12, 'Batz and Sons', '68807 Gateway Parkway', 'bcorbieb@yelp.com', '1605109643');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (13, 'Ritchie, King and Spencer', '065 Crescent Oaks Avenue', 'gmacalindenc@squarespace.com', '9188200708');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (14, 'Powlowski-Douglas', '7716 Melby Point', 'akiernand@foxnews.com', '7717561271');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (15, 'Hoppe-Hodkiewicz', '981 Village Trail', 'jmedlande@sitemeter.com', '6972899057');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (16, 'Pouros-Kohler', '6946 Packers Plaza', 'rlelandf@altervista.org', '8667388105');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (17, 'McGlynn and Sons', '70472 Pine View Way', 'dwitseyg@icio.us', '3677540672');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (18, 'Metz, Mertz and Armstrong', '38 Maywood Lane', 'lkaasmanh@php.net', '5427973740');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (19, 'Davis, Baumbach and Ratke', '058 Jenna Parkway', 'fpeabodyi@hud.gov', '8816647342');
insert into organizatorzy (organizator_id, nazwa_orgaizatora, adres, mail, telefon) values (20, 'Hudson-Robel', '61 Stoughton Plaza', 'csoonhousej@deliciousdays.com', '3899550407');
